os: linux

# Need to install cwiid package

sudo: true

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: GHCVER=8.0.1 STACK_YAML=stack.yaml
    addons: {apt: {packages: [ghc-8.0.1,libcwiid-dev], sources: [hvr-ghc]}}
    #including code for power sysytem
  - env: GHCVER=8.0.1 STACK_YAML=stack.yaml
    addons: {apt: {packages: [ghc-8.0.1,libcwiid-dev], sources: [hvr-ghc]}}
    arch: ppc64le

before_install:
  - date
  - cat /proc/cpuinfo
  - cd ${HOME}
  # Install stack
  - mkdir -p ${HOME}/.local/bin
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ${HOME}/.local/bin '*/stack'
  - export PATH=/opt/ghc/${GHCVER}/bin:/opt/cabal/${CABALVER}/bin:${HOME}/.local/bin:${HOME}/.cabal/bin:${PATH}
  - ghc --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - stack --no-terminal --skip-ghc-check install gtk2hs-buildtools
  - stack --no-terminal --skip-ghc-check install

after_script:
  - date
